### ISSUE TITLE
Interfaces missing in article on Smashing Magazine

### ISSUE THREAD

**Issue by peterennis** [jerrynavi/marvel-client#1]
![Capture883](https://user-images.githubusercontent.com/140737/82131207-a00ff180-9787-11ea-9011-c875e18551b9.PNG)

https://www.smashingmagazine.com/2020/05/introduction-react-ionic/

Needs this:

https://github.com/jerrynavi/marvel-client/tree/master/src/interfaces

**Comment by jerrynavi** [comment]
Hi @peterennis, I tried to leave out the TypeScript bits from the article as otherwise they would have made the article content really long. Glad you found this. If you can leave a comment under the article pointing future readers to this source, that would be really helpful.

**Comment by peterennis** [comment]
Done 👍 

![Capture886](https://user-images.githubusercontent.com/140737/82254874-83e78e00-9908-11ea-9f89-8177ff7df93a.PNG)

**Comment by jerrynavi** [comment]
Thanks!
